name: build-binaries

# TODO: disclaimer to give credit to script authors

# TODO: uncomment this before merging
# on:
#     workflow_dispatch:
#         inputs:
#             scip_hash:
#                 type: string
#                 description: Commit hash for SCIP
#                 required: true
#             soplex_version:
#                 type: string
#                 description: Soplex version to use
#                 required: true
#             ipopt_version:
#                 type: string
#                 description: IPOPT version to use
#                 required: true

on: [push]

jobs:
    macos-arm-build-binaries:
        runs-on: macos-14
        steps:
            - uses: actions/checkout@v3
            - name: Build and install
              run: bash .github/workflows/scripts/macos_arm.bash
            
            - name: ZIP SCIP for MacOS ARM
              run: zip -r ${{ github.workspace }}/upload.zip scip_install/lib scip_install/include scip_install/bin
            
            - uses: actions/upload-artifact@v3
              with:
                path: ${{ github.workspace }}/upload.zip


    macos-build-binaries:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and install
              run: bash .github/workflows/scripts/macos.bash
      
            - name: ZIP SCIP for MacOS
              run: zip -r ${{ github.workspace }}/upload.zip scip_install/lib scip_install/include scip_install/bin

            - uses: actions/upload-artifact@v3
              with:
                path: ${{ github.workspace }}/upload.zip