name: build-binaries

# TODO: disclaimer to give credit to script authors

on:
    workflow_dispatch:
        inputs:
            scip_version:
                type: string
                description: SCIP version to use
                required: true
                default: "9.0.0"
            soplex_version:
                type: string
                description: Soplex version to use
                required: true
                default: "7.0.0"
            ipopt_version:
                type: string
                description: IPOPT version to use
                required: true
                default: "3.14.12"

jobs:
    print-inputs:
      runs-on: ubuntu-latest
      steps:
          - name: Print inputs
            run: |
              echo "SCIP version: ${{github.event.inputs.scip_version}}"
              echo "Soplex version: ${{github.event.inputs.soplex_version}}"
              echo "IPOPT version: ${{github.event.inputs.ipopt_version}}"

    build-binaries:
        strategy:
            matrix:
              include:
                - os: macos-14
                  bash_script: macos_arm.bash
                  id: macos-arm
                - os: macos-latest
                  bash_script: macos.bash
                  id: macos

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - name: Build and install SCIP
              run: |
                export SCIP_VERSION=$(echo "${{github.event.inputs.scip_version}}" | tr -d '.')
                export SOPLEX_VERSION=$(echo "${{github.event.inputs.soplex_version}}" | tr -d '.')
                export IPOPT_VERSION=${{ github.event.inputs.ipopt_version }}
                bash .github/workflows/scripts/${{ matrix.bash_script }}
        
            - uses: actions/upload-artifact@v3
              with:
                path: ${{ github.workspace }}/libscip-${{matrix.id}}.zip

    linux-build-binaries:
        runs-on: ubuntu-latest
        container: quay.io/pypa/manylinux2014_x86_64
        steps:
            - uses: actions/checkout@v3
            - name: Build and install SCIP
              run: |
                export SCIP_VERSION=$(echo "${{github.event.inputs.scip_version}}" | tr -d '.')
                export SOPLEX_VERSION=$(echo "${{github.event.inputs.soplex_version}}" | tr -d '.')
                export IPOPT_VERSION=${{ github.event.inputs.ipopt_version }}
                bash -x .github/workflows/scripts/linux.bash
            - uses: actions/upload-artifact@v3
              with:
                path: ${{ github.workspace }}/libscip-linux.zip

    windows-build-binaries:
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v3
          - uses: msys2/setup-msys2@v2      
      
          - name: Build and install SCIP
            run:  |
              export SCIP_VERSION=$(echo "${{github.event.inputs.scip_version}}" | tr -d '.')
              export SOPLEX_VERSION=$(echo "${{github.event.inputs.soplex_version}}" | tr -d '.')
              export IPOPT_VERSION=${{ github.event.inputs.ipopt_version }}
              bash -x .github/workflows/scripts/windows.bash
            shell: msys2 {0}
          
          - uses: actions/upload-artifact@v3
            with:
              path: ${{ github.workspace }}/libscip-windows.zip

