name: build-binaries

# TODO: disclaimer to give credit to script authors

# TODO: uncomment this before merging
# on:
#     workflow_dispatch:
#         inputs:
#             scip_hash:
#                 type: string
#                 description: Commit hash for SCIP
#                 required: true
#             soplex_version:
#                 type: string
#                 description: Soplex version to use
#                 required: true
#             ipopt_version:
#                 type: string
#                 description: IPOPT version to use
#                 required: true

on: [push]

jobs: 
    # build-binaries:
    #     strategy:
    #         matrix:
    #           include:
    #             - os: macos-14
    #               bash_script: macos_arm.bash
    #             - os: macos-latest
    #               bash_script: macos.bash

    #     runs-on: ${{ matrix.os }}
    #     steps:
    #         - uses: actions/checkout@v3
    #         - name: Build and install SCIP
    #           run: bash .github/workflows/scripts/${{ matrix.bash_script }}
            
    #         - name: ZIP SCIP
    #           run: zip -r ${{ github.workspace }}/upload.zip scip_install/lib scip_install/include scip_install/bin
            
    #         - uses: actions/upload-artifact@v3
    #           with:
    #             path: ${{ github.workspace }}/upload.zip

    linux-build-binaries:
        runs-on: ubuntu-latest
        container: quay.io/pypa/manylinux2014_x86_64
        steps:
            - uses: actions/checkout@v3
            - name: Build and install SCIP
              run: bash .github/workflows/scripts/linux.bash
            - name: ZIP SCIP
              run: zip -r ${{ github.workspace }}/upload.zip scip_install/lib scip_install/include scip_install/bin
            - uses: actions/upload-artifact@v3
              with:
                path: ${{ github.workspace }}/upload.zip